language: cpp
sudo: required
services: docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_script:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

script:
  - ./fetch-grpc.sh
  - ./autogen.sh
  - ./configure
  - make distcheck || (cat protobuf-test-1.0/_build/tests/test-suite.log && exit 1)
